config/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

from pages.views import page_not_found
from words.views import search, import_data_from_json #export_data_to_json,

from .sitemaps import StaticViewSitemap, WordViewSitemap

sitemaps = {'static': StaticViewSitemap, 'words': WordViewSitemap}

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='pages/robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('words/', include('words.urls', namespace='words')),
    path('play/', include('play.urls', namespace='play')),
    # path('export-json/', export_data_to_json, name='export_json'),
    path('import-json/', import_data_from_json, name='import_json'),
    path('', include('pages.urls', namespace='pages')),
    path('', include('sim.urls', namespace='sim')),
    path('django-check-seo/', include('django_check_seo.urls')),
    path('search/', search, name='search'),
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from .views import home_view

app_name = "pages"

urlpatterns = [
    path("", home_view, name="home"),
]

play/urls.py
from django.urls import path
from .views import play_view

app_name = 'play'

urlpatterns = [
    path('', play_view, name='play'),
]

sim/urls.py
from django.urls import path
from . import views

app_name = 'sim'

urlpatterns = [
    path('sign-in', views.sign_in, name='sign_in'),
    path('sign-out', views.sign_out, name='sign_out'),
    path('auth-receiver', views.auth_receiver, name='auth_receiver'),
]

words/urls.py
from django.urls import path
from .views import wordlist_view, word_view

app_name = 'words'

urlpatterns = [
    path('', wordlist_view, name='wordlist'),
    path('<str:word>/', word_view, name='word_view'),
]

pages/templates/base.html
{% load static %}
<html lang="En-en">
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-SBE58EYK2Q"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-SBE58EYK2Q');
    </script>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
      (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
      m[i].l=1*new Date();
      for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
      k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
      (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

      ym(99042430, "init", {
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true,
          webvisor:true
      });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/99042430" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    <title>
      {% if is_home %}
        {{ home_view.domain }}, {{ home_view.title }}
      {% else %}
        {% block title %}{% endblock title %} • {{ home_view.domain }}
      {% endif %}
    </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock %}">
    <link rel="canonical" href="{{ CANONICAL_URL }}">
    <meta property="og:locale" content="en">
    <meta property="og:site_name" content="GuessWrong, Dive into the words">
    <meta property="og:type" content="website">
    {% block og:title %}{% endblock og:title %}
    {% block og:description %}{% endblock og:description %}
    {% block og:image %}{% endblock og:image %}
    <meta property="og:url" content="{{ CANONICAL_URL }}">
    <meta property="og:image:type" content="image/webp">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="yandex-verification" content="473b4503a24d6ee1">
    <script src="https://accounts.google.com/gsi/client" async></script>
    <link href="{% static 'bootstrap-5.3.3-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <link href="{% static 'img/favicon.png' %}" rel="icon" type="image/x-icon">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
    <link href="{% static 'css/play.css' %}" rel="stylesheet">
    
    {% block schemaorg %}{% endblock schemaorg %}
  </head>
  <body class="d-flex flex-column min-vh-100">
    {% include 'navbar.html' %}

    <div class="container text-start my-4 flex-grow-1">
      {% block content %}
      {% endblock content %}
    </div>

    {% include 'footer.html' %}
    <script src="{% static 'bootstrap-5.3.3-dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
  </body>
</html>

pages/templates/footer.html
{% load static %}
<footer class="py-4 mt-auto" style="background-color: var(--night); color: var(--ivory);">
  <div class="container">
    <div class="row">
      <div class="col-md-8 mb-3 mb-md-0">
        <h5 class="mb-3">About project</h5>
        <p class="mb-0">This project is designed to help users learn foreign words through an engaging game that identifies gaps in their knowledge.</p>
      </div>
      <div class="col-md-4 text-md-end d-none">
        <h5 class="mb-3">Follow us</h5>
        <a href="#" class="me-3" style="color: var(--ivory); text-decoration: none;" target="_blank" onmouseover="this.style.color='var(--flash)'" onmouseout="this.style.color='var(--ivory)'">
          <i class="bi bi-facebook" style="font-size: 1.5rem;"></i>
        </a>
        <a href="#" class="me-3" style="color: var(--ivory); text-decoration: none;" target="_blank" onmouseover="this.style.color='var(--flash)'" onmouseout="this.style.color='var(--ivory)'">
          <i class="bi bi-twitter-x" style="font-size: 1.5rem;"></i>
        </a>
        <a href="#" style="color: var(--ivory); text-decoration: none;" target="_blank" onmouseover="this.style.color='var(--flash)'" onmouseout="this.style.color='var(--ivory)'">
          <i class="bi bi-instagram" style="font-size: 1.5rem;"></i>
        </a>
      </div>
    </div>
    <div class="text-center mt-4">
      <p class="mb-0">
        <i class="bi bi-c-circle"></i>
        <a href="/" style="color: var(--ivory); text-decoration: none;" onmouseover="this.style.color='var(--flash)'" onmouseout="this.style.color='var(--ivory)'">
          {{ home_view.domain }}
        </a>
        {{ home_view.current_year }}. All rights reserved.
      </p>
    </div>
  </div>
</footer>

pages/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container position-relative d-flex justify-content-between align-items-center">

    <a class="navbar-brand mx-auto fs-4" href="{% url 'pages:home' %}" style="font-style: italic;">GuessWrong</a>

    <button id="navbar-toggler" class="navbar-toggler custom-toggler position-absolute end-0 me-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <i class="bi bi-three-dots-vertical" id="toggler-icon"></i>
    </button>

    <!-- Collapsible Menu Links -->
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mb-2 mb-lg-0 d-flex align-items-center">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'play:play' %}">Play</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'words:wordlist' %}">Words</a>
        </li>

        <li class="nav-item w-100" style="display: flex; align-items: center;">
          <form 
            method="POST" 
            action="{% url 'search' %}" 
            class="d-flex w-100" 
            onsubmit="return this.searched.value.trim() !== '';"
          >
            {% csrf_token %}
            <div class="input-group">
              <input 
                type="text" 
                class="form-control shadow-none" 
                placeholder="Search for words" 
                name="searched"
              >
              <button type="submit" class="btn btn-secondary">Search</button>
            </div>
          </form>
        </li>
        
        
        

        <!-- Sign in Link for small screens -->
        {% if request.session.user_data %}
        <span class="navbar-text">
          <div class="d-flex align-items-center d-lg-none">
            <!-- <span>Hi, {{ request.session.user_data.given_name }}</span> -->
            <a href="/sign-out" class="nav-link ms-2">Sign out</a>
            <img src="{{ request.session.user_data.picture }}" alt="User picture" class="rounded-circle ms-2" style="width: 30px; height: 30px;">
          </div>
        </span>
        {% else %}
        <li class="nav-item d-lg-none"> <!-- Only visible on small screens -->
          <a class="nav-link" href="{% url 'sim:sign_in' %}">Sign in</a>
        </li>
        {% endif %}
      </ul>
    </div>

    <!-- User Authentication Links for large screens (right-aligned) -->
    <div class="d-none d-lg-flex align-items-center ms-auto">
      {% if request.session.user_data %}
      <span class="navbar-text">
        <div class="d-flex align-items-center">
          <!-- <span>Hi, {{ request.session.user_data.given_name }}</span> -->
          <a href="/sign-out" class="nav-link ms-2">Sign out</a>
          <img src="{{ request.session.user_data.picture }}" alt="User picture" class="rounded-circle ms-2" style="width: 30px; height: 30px;">
        </div>
      </span>
      {% else %}
      <a class="nav-link" href="{% url 'sim:sign_in' %}">Sign in</a>
      {% endif %}
    </div>
  </div>
</nav>