config/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic.base import TemplateView

from pages.views import page_not_found
from words.views import search, import_data_from_json #export_data_to_json,

from .sitemaps import StaticViewSitemap, WordViewSitemap

sitemaps = {'static': StaticViewSitemap, 'words': WordViewSitemap}

urlpatterns = [
    path('robots.txt', TemplateView.as_view(template_name='pages/robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('words/', include('words.urls', namespace='words')),
    path('play/', include('play.urls', namespace='play')),
    # path('export-json/', export_data_to_json, name='export_json'),
    path('import-json/', import_data_from_json, name='import_json'),
    path('', include('pages.urls', namespace='pages')),
    path('', include('sim.urls', namespace='sim')),
    path('django-check-seo/', include('django_check_seo.urls')),
    path('search/', search, name='search'),
]

handler404 = page_not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sim/urls.py
from django.urls import path
from . import views

app_name = 'sim'

urlpatterns = [
    path('sign-in', views.sign_in, name='sign_in'),
    path('sign-out', views.sign_out, name='sign_out'),
    path('auth-receiver', views.auth_receiver, name='auth_receiver'),
]

words/urls.py
from django.urls import path
from .views import wordlist_view, word_view

app_name = 'words'

urlpatterns = [
    path('', wordlist_view, name='wordlist'),
    path('<str:word>/', word_view, name='word_view'),
]

words/models.py
from django.db import models

from cloudinary.models import CloudinaryField


class Example(models.Model):
    word = models.ForeignKey('RealWord', related_name='examples', on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)

    def __str__(self):
        return ""


class Synonym(models.Model):
    word = models.ForeignKey('RealWord', related_name='synonyms', on_delete=models.CASCADE)
    text = models.CharField(max_length=50)

    def __str__(self):
        return ""


class Antonym(models.Model):
    word = models.ForeignKey('RealWord', related_name='antonyms', on_delete=models.CASCADE)
    text = models.CharField(max_length=50)

    def __str__(self):
        return ""


class RealWord(models.Model):
    PART_OF_SPEECH_CHOICES = [
        ('noun', 'Noun'),
        ('verb', 'Verb'),
        ('adjective', 'Adjective'),
        ('adverb', 'Adverb'),
        ('pronoun', 'Pronoun'),
        ('preposition', 'Preposition'),
        ('conjunction', 'Conjunction'),
        ('interjection', 'Interjection'),
        ('numeral', 'Numeral'),
        ('article', 'Article'),
        ('determiner', 'Determiner'),
    ]

    word = models.CharField(max_length=50, unique=True)
    part_of_speech = models.CharField(
        max_length=20,
        choices=PART_OF_SPEECH_CHOICES,
        blank=True,
        null=True
    )
    transcription = models.CharField(max_length=50, blank=True, null=True)
    definition = models.TextField(max_length=1000)
    image = CloudinaryField('image', blank=True, null=True)

    def __str__(self):
        return self.word

    def get_absolute_url(self):
        return f'/words/{self.word}/'

    @staticmethod
    def get_random_word():
        random_id = RealWord.objects.values_list('id', flat=True).order_by('?').first()
        return RealWord.objects.get(id=random_id) if random_id else None

words/forms.py
from django import forms


class JSONUploadForm(forms.Form):
    json_file = forms.FileField(label='Загрузите JSON файл')

words/views.py
import os
import json
from itertools import chain

from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q

from .models import RealWord, Example, Synonym, Antonym
from .serializers import RealWordSerializer


def word_view(request, word):
    word_page = get_object_or_404(RealWord, word__iexact=word)  # игнорируем регистр при поиске

    examples = Example.objects.filter(word=word_page)

    # Проверяем наличие связанных RealWord для синонимов и антонимов с учетом регистра
    synonyms = [
        {
            'text': synonym.text,
            'exists': RealWord.objects.filter(word__iexact=synonym.text).exists()
        }
        for synonym in Synonym.objects.filter(word=word_page)
    ]

    antonyms = [
        {
            'text': antonym.text,
            'exists': RealWord.objects.filter(word__iexact=antonym.text).exists()
        }
        for antonym in Antonym.objects.filter(word=word_page)
    ]

    return render(request, 'words/word.html', {
        'word_page': word_page,
        'examples': examples,
        'synonyms': synonyms,
        'antonyms': antonyms,
    })


# def wordlist_view(request):
#     words = RealWord.objects.all()  # Retrieve all words from the RealWord table
#     return render(request, 'words/wordlist.html', {'words': words})


def wordlist_view(request):
    # Получение всех слов из базы данных
    words = RealWord.objects.all().order_by('word')  # Сортируем слова по алфавиту

    # Создание словаря для организации слов по первой букве
    words_by_letter = {}
    for word in words:
        first_letter = word.word[0].upper()
        if first_letter not in words_by_letter:
            words_by_letter[first_letter] = []
        words_by_letter[first_letter].append(word)

    # Создаем список букв для навигации
    alphabet = sorted(words_by_letter.keys())  # Убедимся, что ключи также отсортированы

    context = {
        'words_by_letter': words_by_letter,
        'alphabet': alphabet,
    }

    return render(request, 'words/wordlist.html', context)


# def export_data_to_json(request):
#     # Получаем все данные из модели RealWord
#     words = RealWord.objects.all()

#     # Сериализуем данные
#     serializer = RealWordSerializer(words, many=True)
#     data = serializer.data

#     # Сохраняем JSON в файл
#     file_path = os.path.join(settings.MEDIA_ROOT, 'exported_data.json')
#     with open(file_path, 'w', encoding='utf-8') as f:
#         json.dump(data, f, ensure_ascii=False, indent=4)

#     return JsonResponse({'message': 'Data exported successfully!', 'file_path': file_path})


@csrf_exempt
def import_data_from_json(request):
    if request.method == 'POST':
        # Проверяем, был ли передан файл
        if 'file' not in request.FILES:
            return JsonResponse({'error': 'No file provided'}, status=400)

        json_file = request.FILES['file']

        # Читаем содержимое файла и парсим JSON
        try:
            data = json.load(json_file)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON file'}, status=400)

        # Обрабатываем каждый элемент в JSON-данных
        for word_data in data:
            # Создаем или получаем экземпляр RealWord
            word, created = RealWord.objects.get_or_create(
                word=word_data['word'],
                defaults={
                    'transcription': word_data.get('transcription', ''),
                    'definition': word_data.get('definition', ''),
                    'image': word_data.get('image', None)
                }
            )

            # Добавляем примеры, синонимы и антонимы
            if 'examples' in word_data:
                for example in word_data['examples']:
                    Example.objects.get_or_create(word=word, text=example['text'])

            if 'synonyms' in word_data:
                for synonym in word_data['synonyms']:
                    Synonym.objects.get_or_create(word=word, text=synonym['text'])

            if 'antonyms' in word_data:
                for antonym in word_data['antonyms']:
                    Antonym.objects.get_or_create(word=word, text=antonym['text'])

        return JsonResponse({'message': 'Data imported successfully!'})

    return JsonResponse({'error': 'Invalid request method'}, status=405)


def search(request):
    if request.method == 'POST':
        searched_query = request.POST['searched'].strip()

        # Получаем результаты сначала по слову, затем по определению
        word_results = RealWord.objects.filter(word__icontains=searched_query)
        definition_results = RealWord.objects.filter(
            definition__icontains=searched_query
        ).exclude(id__in=word_results)  # Исключаем дубликаты

        # Объединяем результаты: сначала по слову, затем по определению
        searched_results = list(chain(word_results, definition_results))

        if not searched_results:
            return render(request, 'pages/search.html', {
                'message': f"Nothing found for the query <strong>{searched_query}</strong>. Please try again.",
                'searched_query': searched_query
            })
        else:
            return render(request, 'pages/search.html', {
                'searched': searched_results,
                'searched_query': searched_query
            })
    else:
        return render(request, 'pages/search.html', {})

words/templates/words/word.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block title %}
  Word {{ word_page.word|upper }} → Meaning, examples, synonyms & antonyms
{% endblock title %}

{% block description %}
  ✅ Discover the meaning of the word '{{ word_page.word|upper }}' with detailed descriptions, examples, and synonyms. Expand your vocabulary effectively!
{% endblock description %}

{% block og:title %}
  <meta property="og:title" content="Word {{ word_page.word|upper }} → Meaning, examples, synonyms & antonyms">
{% endblock og:title %}

{% block og:description %}
  <meta property="og:description" content="✅ Discover the meaning of the word '{{ word_page.word|upper }}' with detailed descriptions, examples, and synonyms. Expand your vocabulary effectively!">
{% endblock og:description %}

{% if word_page.image %}
  {% block og:image %}
    <meta property="og:image" content="{{ word_page.image.url }}">
  {% endblock og:image %}
{% endif %}

{% block schemaorg %}
  <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Article",
      "name": "{{ word_page.word|capfirst }}",
      {% if word_page.image %}
        "image": "{{ word_page.image.url }}",
      {% endif %}
      "url": "{{ CANONICAL_URL }}"
    }
  </script>
{% endblock schemaorg %}

{% block content %}
  <div class="container my-4">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/words/">Words</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ word_page.word|capfirst }}</li>
      </ol>
    </nav>

    <div class="row justify-content-center">
      <div class="col-xxl-3 col-xl-3">
        <div class="sticky-top d-none d-xl-block" style="top: 20px;">
          <div class="list-group mb-4">
            {% if examples %}<a href="#meanings" class="list-group-item list-group-item-action dotted-link">Meanings</a>{% endif %}
            {% if examples %}<a href="#examples" class="list-group-item list-group-item-action dotted-link">Examples</a>{% endif %}
            {% if synonyms %}<a href="#synonyms" class="list-group-item list-group-item-action dotted-link">Synonyms</a>{% endif %}
            {% if antonyms %}<a href="#antonyms" class="list-group-item list-group-item-action dotted-link">Antonyms</a>{% endif %}
          </div>
        </div>
        
        <div class="d-block d-xl-none">
          <div class="list-group mb-4">
            {% if examples %}<a href="#meanings" class="list-group-item list-group-item-action dotted-link">Meanings</a>{% endif %}
            {% if examples %}<a href="#examples" class="list-group-item list-group-item-action dotted-link">Examples</a>{% endif %}
            {% if synonyms %}<a href="#synonyms" class="list-group-item list-group-item-action dotted-link">Synonyms</a>{% endif %}
            {% if antonyms %}<a href="#antonyms" class="list-group-item list-group-item-action dotted-link">Antonyms</a>{% endif %}
          </div>
        </div>
        
      </div>

      <div class="col-xxl-9 col-xl-9">
        <h1 class="fs-6">Word <strong>{{ word_page.word|upper }}</strong>: meanings, synonyms & antonyms</h1>
        <span class="mb-4 text-center d-block fs-1">{{ word_page.word }}</span>

        {% if word_page.transcription %}
          <p class="mb-4 text-center">🇺🇸 [{{ word_page.transcription }}]</p>
        {% endif %}

        <h2 id="meanings">Meanings</h2>
        <p class="text-left">{{ word_page.definition|capfirst }}</p>

        {% if word_page.image %}
          <div class="text-start mb-4">
            <img src="{{ word_page.image.url }}" alt="English word {{ word_page.word|capfirst }}" 
                class="img-fluid rounded me-3" style="width: 435px; height: 435px; object-fit: cover;">
          </div>
        {% endif %}

        {% if examples %}
          <h2 id="examples">Examples</h2>
          <ul>
            {% for example in examples %}
              <li><i>{{ example.text|highlight_word:word_page.word|safe }}</i></li>
            {% endfor %}
          </ul>
        {% endif %}

        {% if synonyms %}
          <h2 id="synonyms">Synonyms</h2>
          <p class="mb-4">
            {% for synonym in synonyms %}
              {% if synonym.exists %}
                <a href="{% url 'words:word_view' synonym.text|lower %}" class="text-decoration-none">{{ synonym.text|lower }}</a>
              {% else %}
                {{ synonym.text|lower }}
              {% endif %}
              {% if not forloop.last %}• {% endif %}
            {% endfor %}
          </p>
        {% endif %}

        {% if antonyms %}
          <h2 id="antonyms">Antonyms</h2>
          <p class="mb-4">
            {% for antonym in antonyms %}
              {% if antonym.exists %}
                <a href="{% url 'words:word_view' antonym.text|lower %}" class="text-decoration-none">{{ antonym.text|lower }}</a>
              {% else %}
                {{ antonym.text|lower }}
              {% endif %}
              {% if not forloop.last %}• {% endif %}
            {% endfor %}
          </p>
        {% endif %}

      </div>
    </div>
  </div>
{% endblock content %}

words/templates/words/wordlist.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}

{% block title %}
  Wordlist
{% endblock title %}

{% block description %}
  ✅ Explore a list of English words with meanings, examples, and synonyms to expand your vocabulary and improve language skills
{% endblock description %}

{% block content %}
  <div class="container mt-5">
    <h1 class="mb-4">Word List</h1>

    <!-- Alphabet Navigation -->
    <div class="mb-4">
      <ul class="list-inline">
        {% for letter in alphabet %}
          <li class="list-inline-item">
            <a href="#letter-{{ letter }}" class="text-decoration-none">{{ letter }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>

    <!-- Word Groups by Letter -->
    <div class="row">
      {% for letter, words in words_by_letter.items %}
        {% if words %}
          <div class="col-md-3 mb-4">
            <h2 id="letter-{{ letter }}">{{ letter }}</h2>
            <ul class="list-group">
              {% for word in words %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <a href="{% url 'words:word_view' word=word.word %}" class="text-decoration-none">{{ word.word }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock content %}